// <auto-generated />
using HSM.WinService.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HSM.WinService.Core.Migrations
{
    [DbContext(typeof(HsmDbContext))]
    [Migration("20240726204210_Migratee3")]
    partial class Migratee3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("HSM.WinService.Core.Entitites.ActionCode", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action_En")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Action_In_English");

                    b.Property<string>("Action_Ka")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Action_in_Georgian");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Code_Of_Action");

                    b.Property<bool>("IsEmergencySituation")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActionId");

                    b.ToTable("ActionCodes");

                    b.HasData(
                        new
                        {
                            ActionId = 1,
                            Action_En = "Room one Have Error, Check Air Condition",
                            Action_Ka = "პირველ ოთახს აქვს ხარვეზი, შეამოწმე თერმოსტატი!",
                            Code = "101",
                            IsEmergencySituation = false
                        });
                });

            modelBuilder.Entity("HSM.WinService.Core.Entitites.ContactInfo", b =>
                {
                    b.Property<int>("ContactInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContactInfoId");

                    b.ToTable("ContactInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
