// <auto-generated />
using HSM.WinService.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HSM.WinService.Core.Migrations
{
    [DbContext(typeof(HsmDbContext))]
    [Migration("20240726165422_Migrate")]
    partial class Migrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("HSM.WinService.Core.Entitites.ActionCode", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action_En")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Action_In_English");

                    b.Property<string>("Action_Ka")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Action_in_Georgian");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Code_Of_Action");

                    b.HasKey("ActionId");

                    b.ToTable("ActionCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
